### ISSUE TITLE
Implement designs for print to play offline page

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#10]
Blocked by #32 

This will cover the /print page where users can select a card deck and/or generate a number of tablas to print off for playing offline.

<img width="725" alt="Screen Shot 2022-08-18 at 9 57 29 AM" src="https://user-images.githubusercontent.com/6540763/185452355-2d7057ab-ddea-48a8-8364-b304f0c54be2.png">

**Comment by mackenzie-o** [comment]
Between new projects at work and upcoming vacation, I won't be able to finish this for a while. I know download was a high priority feature, so I'm going to unassign this in case someone else will be able to pick this up. What I've done thus far is up at https://github.com/JessRudder/loteria-cielo/pull/45 if anyone wants to branch off of it!

**Comment by csmlo** [comment]
> Between new projects at work and upcoming vacation, I won't be able to finish this for a while. I know download was a high priority feature, so I'm going to unassign this in case someone else will be able to pick this up. What I've done thus far is up at https://github.com/JessRudder/loteria-cielo/pull/45 if anyone wants to branch off of it!

Thank you Mackenzie!

**Comment by gdomingu** [comment]
I believe this was addressed with https://github.com/JessRudder/loteria-cielo/pull/45
