### ISSUE TITLE
Add Dilla Xhon audio to the game

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#13]
We received the audio for Dilla Xhon - https://drive.google.com/drive/folders/1oBpnYBkbdQGcSd2OQeaSISi5ANJ29b6F

Add it to the game and make sure that the timing for drawing the next card works with the length of the audio.

**Comment by csmlo** [comment]
Rafa Diaz to take a look at this issue

**Comment by rcxr** [comment]
Currently working on this.

**Comment by JessRudder** [comment]
Closed by #29
