### ISSUE TITLE
Document how to push to the heroku app

### ISSUE THREAD

**Issue by mackenzie-o** [JessRudder/loteria-cielo#18]
Seems like a handy section to add to the README. Probably need to figure out how to get permissions as well!

**Comment by mackenzie-o** [comment]
Currently live at http://loteria-cielo.herokuapp.com/

**Comment by gdomingu** [comment]
Since heroku no longer supports a free tier I believe we are going to try to host this on github pages for now and see how that goes. Closing since this is no longer relevant for now.
