### ISSUE TITLE
Add ability to select a deck and generate a number of tablas (boards) to print

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#2]
Related to #1 

The CIELO team has requested the ability to print out card decks and tablas (boards) so they can play offline with friends and family.

In order to support this, we need to add the ability to select a deck of cards, allow the player to choose a number of tablas for us to generate and give them the option to print a physical copy.

This should be done on a new end point (`/print` perhaps). This end point will be the same one that allows a person to select a card deck and print it.

We don't currently have designs for these pages, but this ticket would be to implement the functionality (we will make it look nice once we've got designs)

**Comment by gdomingu** [comment]
I believe this was solved with https://github.com/JessRudder/loteria-cielo/pull/45
