### ISSUE TITLE
Request to switch out two cards from @sofiatwins

### ISSUE THREAD

**Issue by csmlo** [JessRudder/loteria-cielo#24]
Ask from @sofiatwins on whether we can replace images, names or use a new card for two cards to move away from stereotypes and builds a sense of identity in the players:

![image (5)](https://user-images.githubusercontent.com/70599317/182263258-38341e7b-f0dd-4056-93c7-1156ae4797a5.png)

![image (6)](https://user-images.githubusercontent.com/70599317/182263256-1087361d-1d96-4421-9a05-ded3f64a78b2.png)

**Comment by JessRudder** [comment]
Closed by #25
