### ISSUE TITLE
Add "print to play offline page"

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#32]
Right now, when you click "Version impressa" or "Print version", nothing happens. 

We need that button to take folks to a page where they can:
 - Print 1 set of the loteria cards
 - Choose a number of tablas that will be generated and printed
 
Here is the page design (it is fine for the person that grabs this ticket to focus on implementing the functionality as we have another ticket for implementing the design on the page (though, if you work best doing it all at the same time, feel free to implement it at the same time):

<img width="725" alt="Screen Shot 2022-08-18 at 9 57 29 AM" src="https://user-images.githubusercontent.com/6540763/185452997-45f4ed11-01b2-458f-a16d-2122251064fb.png">

**Comment by gdomingu** [comment]
@JessRudder do you know where we could get the icons for the cards?

**Comment by csmlo** [comment]
> @JessRudder do you know where we could get the icons for the cards? 

I think I can help with that! Do you mean the cars images?

Translation Words are [here](https://docs.google.com/document/d/1CCwekoEMKzffnAhU-41ZLajrnTYTLXv7eHL3dWMFxAc/edit?usp=sharing)

Card images are [here](https://drive.google.com/drive/folders/1jmRkaNWEZa7ly8YDknJdVVJ4XKuS1pNe?usp=sharing)

**Comment by gdomingu** [comment]
@csmlo thank you! I'm going to be working on this tonight and this weekend. It says I need access for the word doc.

**Comment by gdomingu** [comment]
@csmlo ah also I meant these images.
<img width="170" alt="Screen Shot 2022-10-14 at 9 30 14 PM" src="https://user-images.githubusercontent.com/4443635/195968733-a0346dc4-f59a-4573-8e48-defe6c96937f.png">

**Comment by csmlo** [comment]
@gdomingu Updated access!

**Comment by csmlo** [comment]
> @csmlo ah also I meant these images.
> <img width="170" alt="Screen Shot 2022-10-14 at 9 30 14 PM" src="https://user-images.githubusercontent.com/4443635/195968733-a0346dc4-f59a-4573-8e48-defe6c96937f.png">
> 

Apologies! Try this [file](https://www.figma.com/file/3fcQKsuuVd3HbMemIX1MdI/Loteria---Social-Impact?node-id=401%3A6)?

**Comment by gdomingu** [comment]
Thank you @csmlo

**Comment by gdomingu** [comment]
Fixed with https://github.com/JessRudder/loteria-cielo/pull/45
