### ISSUE TITLE
On lobby page replace code with full link to the lobby

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#33]
Currently, on the lobby page we provide the user with the code for their specific game.

Instead, we should provide them with a link (hopefully with one click copy) to the lobby itself.

<img width="712" alt="Screen Shot 2022-08-18 at 10 07 51 AM" src="https://user-images.githubusercontent.com/6540763/185454618-f9441158-77ea-4857-a035-0d05d16954ba.png">

**Comment by gdomingu** [comment]
@emisanada can we close this issue? It looks like you merged in the logic?

**Comment by gdomingu** [comment]
Closing for now, let's reopen if it still needs to be done.
