### ISSUE TITLE
Site is missing a TLS certificate. 

### ISSUE THREAD

**Issue by csmlo** [JessRudder/loteria-cielo#35]
Site is missing a TLS certificate. Shows a "Not Secure". Tested on ChromeOS but this is applicable to all OS and all Browsers. Additionally, Google search will down rank your site if it considers it insecure.

**Comment by djensenius** [comment]
@csmlo will the current domain be the final URL for the project, and might be something we can do through heroku. Does someone currently manage that?

**Comment by csmlo** [comment]
Curre

> @csmlo will the current domain be the final URL for the project, and might be something we can do through heroku. Does someone currently manage that?

Good question! Currently we don't have anyone managing this and I think the team and I are open to changing the URL as needed.

We might have some budget for hosting if needed as well.

**Comment by gdomingu** [comment]
I believe this is taken care of for us with github pages so I am closing for now.
