### ISSUE TITLE
Adjust game card positioning

### ISSUE THREAD

**Issue by csmlo** [JessRudder/loteria-cielo#36]
Feedback from user on location of game card:
![Untitled drawing (4)](https://user-images.githubusercontent.com/70599317/185460774-d822c189-2722-470a-a395-da4ca4d5f566.jpg)

**Comment by JessRudder** [comment]
@fmacar3na here's the planned design for this page (just throw a placeholder in for the how to win section):

<img width="714" alt="Screen Shot 2022-08-18 at 11 33 33 AM" src="https://user-images.githubusercontent.com/6540763/185468840-980e70a6-22ba-4aba-a4bb-9a250cbca633.png">
