### ISSUE TITLE
missing or mistyped audio file

### ISSUE THREAD

**Issue by GretaP** [JessRudder/loteria-cielo#39]
Line that should be changed:
https://github.com/JessRudder/loteria-cielo/blob/0a91107a7e696b7ec750eb799d0d2762d6c627ab/src/Loteria/barajas.js#L11

While playing the game using dilla-xhon deck, saw error that the following audio file didn't exist:
https://storage.googleapis.com/loteria-cielo/audio/dx-zoogocho/01-yellhio.wav

**Comment by JessRudder** [comment]
Thanks for the feedback. The audio file has been added in!
