### ISSUE TITLE
[Bug] 🐞 `Print Version` button does nothing

### ISSUE THREAD

**Issue by J3nnie** [JessRudder/loteria-cielo#55]
### Current behaviour:
Nothing happens when clicking the `Print Version` \ `Version Impresa` button

(Firefox 104.0.2 (64-bit))

###
Something happens when clicking the `Print Version` \ `Version Impresa` button, or hide the button

**Comment by gdomingu** [comment]
+1 I noticed this as well.

**Comment by gdomingu** [comment]
What is it supposed to do exactly?

**Comment by gdomingu** [comment]
Closing because it is a duplicate of https://github.com/JessRudder/loteria-cielo/issues/32
