### ISSUE TITLE
[Bug] 🐞 Sharable link is not copyable when not on HTTPs page

### ISSUE THREAD

**Issue by J3nnie** [JessRudder/loteria-cielo#59]
### Current behaviour
When in unsecure (not httpS) game lobby page, the sharable link is visible but not copy-able

(Firefox 104.0.2 (64-bit))

### Expected
It is possible to copy the sharable link

**Comment by gdomingu** [comment]
I don't think this will be an issue now that we are using github pages and keeps us on ssl site. Please reopen if still an issue.
