### ISSUE TITLE
Allow people to select language for website

### ISSUE THREAD

**Issue by JessRudder** [JessRudder/loteria-cielo#6]
Note: This is separate from selecting the language of the deck that you want to play the game with. This will change the language that's used for buttons, menus, help text, etc.

- [x] Figure out how we're going to manage internationalization for the site
- [ ] Get translations for each of the languages we want to support (Spanish, English and, ideally Dilla Xhon)
- [ ] Design for how people will select the language

**Comment by mackenzie-o** [comment]
We have an internationalization system in place, and translations for en and es!

We'll need someone external (from CIELO?) for help with Dilla Xhon, and updated designs for selecting the UI language.

**Comment by streats** [comment]
Is this still to be done? I see an English button that switches the UI language to English so it seems like this has been implemented?
<img width="917" alt="Screenshot 2022-10-04 at 19 09 15" src="https://user-images.githubusercontent.com/12902836/193893793-2fbd92dc-4fda-4b9e-87e5-a316ee391338.png">

**Comment by JessRudder** [comment]
I believe this is complete! Thanks for checking (and thanks to @mackenzie-o for the implementation!)
